name: .NET CI/CD

on:
  push:
    branches: [ "development" ]

jobs:
  ci:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ERP

    - name: Restore dependencies
      working-directory: ERP
      shell: cmd
      run: dotnet restore ERPSystem.PresentationLayer\ERPSystem.PresentationLayer.csproj

    - name: Build
      working-directory: ERP
      shell: cmd
      run: dotnet build ERPSystem.PresentationLayer\ERPSystem.PresentationLayer.csproj --configuration Release --no-restore

    - name: Publish
      working-directory: ERP
      shell: cmd
      run: dotnet publish ERPSystem.PresentationLayer\ERPSystem.PresentationLayer.csproj -c Release -o publish
